export {default as Feature } from './features/Feature'
export {default as Footer } from './footer/Footer'
export {default as Header } from './header/Header'
export {default as Possibility } from './possibility/Possibility'
export {default as Whatgpt3 } from './whatgpt3/Whatgpt3'